# CircleCI configuration file
version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
jobs:
  # Job one with a unique name
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Say hello to YAML!"
  # Job two with a unique name
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Say Worls to YAML!"

workflows:
  # Name of workflow
  welcome:
    # List of jobs that will run
    jobs:
      - welcome/run
      - print_hello
      - print_world
